### ISSUE TITLE
config option to choose local cardano-node for transactions

### ISSUE THREAD

**Issue by peterVG** [Python-Cardano/pycardano#102]
Currently you can change the Network setting from Network.TESTNET to Network.MAINNET. 

Firstly, it's not clear which "Testnet" version this if referring to. It looks like its the "legacy" (broken) testnet still being run by IOG but could (should) be the PREVIEW and/or the PREPROD network. It would be nice if you choose explicitely.

Secondly, it would be nice not to rely on a third-party API like Blockfrost for chain data but instead use your own copy from your cardano-node db. Can we add a config option to PyCardano to use a local node for its read/write transactions?

**Comment by cffls** [comment]
When the library was created, there were only one testnet and mainnet, so I simply used `Network` to distinguish the network. `Network` type is not intended to identify the chain, it should be only used to create cardano address. I could probably remove `Network` type from the parameter of BlockFrost chain context. Also, if you want to use a specific network in BlockFrost, you can pass the API url to `base_url` param, see this post here: https://github.com/cffls/pycardano/discussions/83#discussioncomment-3549922

An alternative to Blockfrost chain context we have implemented is [Ogmios chain context](https://github.com/cffls/pycardano/blob/main/pycardano/backend/ogmios.py), which allows you to run everything locally without depending on a thrid-party API. [This](https://github.com/cffls/pycardano/blob/main/integration-test/test/base.py) is an example where we use Ogmios chain context to get and submit transactions to a local chain.

**Comment by peterVG** [comment]
Cool. Thanks for the explanation. I will check out the Ogmios option.

**Comment by cffls** [comment]
Closing this issue as the solution has been suggested.
