### ISSUE TITLE
Cannot get proper policy hash from policy

### ISSUE THREAD

**Issue by huths0lo** [Python-Cardano/pycardano#104]
I'm loading my policy skey from the json that is created when you generate the keys from cardano-cli.  I can read those fine.  When I create a vkey from it, the result is identical to loading the vkey from json.  So I know the skey and vkey are jiving.  When I use the InvalidHereafter, I produce the same hash as the policy script.  So the policy skey, vkey, and script are all jiving.  But when I go to spit out the hash from the policy, I cannot get it to match my policy id.  I can see from the tx submission that that is exactly what its complaining about.  Its saying I dont have enough assets from policy a, and trying to mint assets from policy b.  Below is the code to create the key, the tx submission error, and the signed tx data:

submit_transaction(data)
'transaction submit error ShelleyTxValidationError ShelleyBasedEraBabbage (ApplyTxError [UtxowFailure (UtxoFailure (FromAlonzoUtxoFail (ValueNotConservedUTxO (Value 1996994043 (fromList [(PolicyID {policyID = ScriptHash "a3680e96ca0587893b878040be0adb3a08646c721a46b74fd25433c0"},fromList [(43617264616e6f4275647a464230303233,1)])])) (Value 1996994043 (fromList [(PolicyID {policyID = ScriptHash "810cdc9a4e4106e5fec73d25c417948af4fb18b9ec9c6b791074ef9f"},fromList [(43617264616e6f4275647a464230303233,1)])])))))])'

def compile_policy(mint_skey, mint_script):
    policy = None
    if mint_skey != None:
        sk = PaymentSigningKey.from_json(json.dumps(mint_skey))  ### THE mint_skey VARIABLE HAS THE POLICY SKEY JSON
        vk = PaymentVerificationKey.from_signing_key(sk)
        pub_key_policy = ScriptPubkey(vk.hash())
        if 'scripts' in mint_script:
            must_before_slot = InvalidHereAfter(mint_script['scripts'][0]['slot'])  #### THE mint_script VARIABLE HAS THE POLICY SCRIPT JSON
            policy = ScriptAll([pub_key_policy, must_before_slot])
        else:
            policy = ScriptAll([pub_key_policy])
    return policy

signed_tx
{'auxiliary_data': AuxiliaryData(data=AlonzoMetadata(metadata={721: {'840e45a88f8ef46222878306752d04df46fb01e38f4392304426ad70': {'CardanoBudzFB0023': {'image': 'ipfs://QmQNQKP6jYpW83jNTtnGoiqtLBWyN3w12dLakvMGUpAcvG',
                                                                                                                                                        'name': 'Cardano '
                                                                                                                                                                'Budz '
                                                                                                                                                                'Fully '
                                                                                                                                                                'Baked '
                                                                                                                                                                '#0023'}}}},
                                                     native_scripts=None,
                                                     plutus_scripts=None)),
 'transaction_body': {'auxiliary_data_hash': AuxiliaryDataHash(hex='2387f7e567e24e5e4bf6e1e3728af43743144ab7e342ad858ad4028dcc0ee183'),
 'certificates': None,
 'collateral': None,
 'fee': 193582,
 'inputs': [{'index': 0,
 'transaction_id': TransactionId(hex='57254cdf2de7e38527080e5caa28898877571150a20acc5c231b09bdda934bb5')}],
 'mint': {ScriptHash(hex='a3680e96ca0587893b878040be0adb3a08646c721a46b74fd25433c0'): {AssetName(b'CardanoBudzFB0023'): 1}},
 'network_id': None,
 'outputs': [{'address': addr_test1vpyzhkrtv4xprtj9z5e3p3e2jrp56wzlaxpaxk7p3gxrdmcph2gph,
 'amount': {'coin': 1994800461, 'multi_asset': {}},
 'datum_hash': None},
             {'address': addr_test1vpyzhkrtv4xprtj9z5e3p3e2jrp56wzlaxpaxk7p3gxrdmcph2gph,
 'amount': {'coin': 2000000,
 'multi_asset': {ScriptHash(hex='810cdc9a4e4106e5fec73d25c417948af4fb18b9ec9c6b791074ef9f'): {AssetName(b'CardanoBudzFB0023'): 1}}},
 'datum_hash': None}],
 'required_signers': None,
 'script_data_hash': None,
 'ttl': 76898386,
 'update': None,
 'validity_start': None,
 'withdraws': None},
 'transaction_witness_set': {'bootstrap_witness': None,
 'native_scripts': [ScriptAll(_TYPE=1,
                              native_scripts=[ScriptPubkey(_TYPE=0,
                                                           key_hash=VerificationKeyHash(hex='83eac3c8076a56efe62854089cd36fdb6b1157adc6a0a085c0992c37')),
                                              InvalidHereAfter(_TYPE=5,
                                                               after=81927623)])],
 'plutus_data': None,
 'plutus_script': None,
 'redeemer': None,
 'vkey_witnesses': [{'signature': b'\xb3\xb85#\xa8\xb0\x89\xceJ\x8e<\x1b\xac\x8e\xa2XU\xca\xe7\xc9'
              b'\xb0i\xbepc\xb1\x07\xc0\xc8\xe3\xda\x93J\xd3\x85\xf0'
              b'\x002\x03\xd7\x99\x9c\x83\xdb)`\x80\xc0D\xf1\r\xd1\xa6\xd4\x01/'
              b'\t\xda!\x9a9h\xe8\x06',
 'vkey': {"type": "PaymentVerificationKeyShelley_ed25519", "description": "Payment Verification Key", "cborHex": "58202027d9ab58c8b6ef08c158078bf753426cf0e4cdb4cb5d64159cd6f4aa299a7b"}},
                    {'signature': b'\t\n{w\xcbs\xa5\xf5zZ\xec\xfd\xb6O%\xd6\x1d\x04\xcc\xd2'
              b'\xcb\x8f\x99#\xfe\xca\x9eDx@\x17Xn\xb8\xa3\xe1\xc0\x9e\xca\x1b'
              b"u\xa4.\xeb\xe9\x0f3\x8d\x8a\x8aH'\xd4\xb3\xa7\xb3\xea\xe9\x00}"
              b'c\xafL\t',
 'vkey': {"type": "PaymentVerificationKeyShelley_ed25519", "description": "Payment Verification Key", "cborHex": "5820d36baff3fc391af90089b347e4db9c785c6716843d366b222028413baf6897d4"}}]},
 'valid': True}

**Comment by huths0lo** [comment]
In fact to add to this, I just did another test. I went back and set my output with the assets (the ones being minted in the tx) to the same policy id hash that gets generated, and this time the tx went through.  The big challenge here, is that even if I use the same keys, every time I restart my python interpreter, the policy hash changes.

Without restarting my interpreter, I was able to burn the same assets I created.  So I just need to find a way to either extract the policy id from the keys correctly, or just be able to load my policy id directly, instead of using the pycardano functions.

aka policy_id = 'abcede'
instead of policy_id = policy.hash() (of which policy was generated with pycardano functions)

**Comment by huths0lo** [comment]
I was able to work around it by skipping all the steps that generate the policy info, and instead use this single command to read in the json contents of the policy script.

policy = InvalidHereAfter.from_dict(raw_tx['mint_script'])

**Comment by cffls** [comment]
Hi @huths0lo , in most cases, minting policy should be generated only once, after which the policy id should be loaded from somewhere deterministic, e.g. file, environment variable. It is better to separate the code into two parts, where the first part generates the policy, and the second uses that policy to mint and burn tokens. You can use [`to_dict`](https://github.com/cffls/pycardano/blob/main/pycardano/nativescript.py#L96) function of a native script policy to convert it to a dictionary that could be saved as a json file, and use [`from_dict`](https://github.com/cffls/pycardano/blob/main/pycardano/nativescript.py#L56) to restore the policy from a json.

**Comment by cffls** [comment]
Closing this issue since the question has been answered.
