### ISSUE TITLE
Feature request: address.balance() helper function

### ISSUE THREAD

**Issue by peterVG** [Python-Cardano/pycardano#115]
Provide a function that returns the current balance of (t)ADA at a valid address.

**Comment by cffls** [comment]
Requested feature is included in this PR: https://github.com/Python-Cardano/pycardano/pull/89

**Comment by peterVG** [comment]
Ah nice! Just spotted them:

```
w.utxos  # list of wallets UTXOs
w.ada  # view total amount of ADA
w.lovelace  # view total amount of lovelace
w.tokens  # get a list of all tokens in the wallet
```
https://github.com/Python-Cardano/pycardano/pull/89/files#diff-7960e6108869da9949251abe0ca4c49ad6fea21656bee5a3720f32955dcaf7a1
