### ISSUE TITLE
Docs for adding arbitrary datum value to .add_output method

### ISSUE THREAD

**Issue by peterVG** [Python-Cardano/pycardano#116]
This works:
```
builder.add_output(TransactionOutput.from_primitive([outaddress, 99900000]))
```

But now I would like to add some arbitrary datum value to my output UTXO. This doesn't work:

```
builder.add_output(TransactionOutput.from_primitive([outaddress, 99900000, datum="my_value"]))
```

Neither does:
```
builder.add_output(TransactionOutput(Datum.from_primitive("my_value")))
```

**Comment by peterVG** [comment]
I'd also like clarity on how to add `ttl` and `reference_inputs` to the TransactionBuilder TransactionOutput as per the API here:
https://pycardano.readthedocs.io/en/latest/api/pycardano.transaction.html#pycardano.transaction.TransactionOutput

There are helper functions for things like `add_input_address` but there is no equivalent `add_reference_inputs` or `add_ttl`.

Trying to pass it as a function parameter value results:
```
builder = TransactionBuilder(context=context, reference_inputs=["test1", "test2"])`
>>>TypeError: TransactionBuilder.__init__() got an unexpected keyword argument 'reference_inputs'
```

```
Trying to add it to the object after it's instantiated also fails to build a proper transaction:
builder = TransactionBuilder(context)`
builder.reference_inputs=["test1", "test2"]
.
.
>>>blockfrost.utils.ApiError: {'error': 'Bad Request', 'message': '"transaction read error RawCborDecodeError [DecoderErrorDeserialiseFailure
```

**Comment by peterVG** [comment]
This code here appears to be adding reference_inputs to the utxo.output.script but, again, not sure where to initially set that reference input value.

https://github.com/Python-Cardano/pycardano/blob/c5430c0137b72bfe401a9eec4b94df97b9187999/pycardano/txbuilder.py#L224-L227

**Comment by cffls** [comment]
The docstring of TransactionOutput already provided a [datum field](https://pycardano.readthedocs.io/en/latest/api/pycardano.transaction.html#pycardano.transaction.TransactionOutput.datum). I think it is straightforward to write correct code by following typings in the doc string. Do you think we can close this one or if there is anything you think is missing?

**Comment by peterVG** [comment]
Yes. Agreed. Thanks for the extra context and keep up the great work!
