### ISSUE TITLE
Document how to add reference_inputs when using TransactionBuilder

### ISSUE THREAD

**Issue by peterVG** [Python-Cardano/pycardano#118]
It's not obvious how to set values for the reference_inputs property and add it to a TransactionBody, as per the API here:
https://pycardano.readthedocs.io/en/latest/api/pycardano.transaction.html#pycardano.transaction.TransactionBody

I can add another TransactionBuilder property like `ttl` as part of the object instantiation, e.g.
`builder = TransactionBuilder(context=context, ttl=2024)`

But trying to do the same for the `reference_inputs` property results in:
```
builder = TransactionBuilder(context=context, reference_inputs=["testing1", "testing2"])
>>>TypeError: TransactionBuilder.__init__() got an unexpected keyword argument 'reference_inputs'
```

Trying to add it to the object after it's instantiated also fails to build a proper transaction:
```
builder = TransactionBuilder(context)`
builder.__set__(self, reference_inputs, {"test1", "test2"})
>>>AttributeError: 'TransactionBuilder' object has no attribute '__set__'. Did you mean: '__eq__'?
```

This code here appears to be adding reference_inputs to the utxo.output.script but, again, not sure where to initially set that reference input value.

https://github.com/Python-Cardano/pycardano/blob/c5430c0137b72bfe401a9eec4b94df97b9187999/pycardano/txbuilder.py#L224-L227

**Comment by cffls** [comment]
Because reference inputs under txbuilder is an empty set by default, you need to add reference inputs like this:

```python
builder.reference_input.add(my_input)
```
or this:

```python
builder.reference_input = {my_input1, my_input2}
```

You can also find an example of using reference script in this test: https://github.com/Python-Cardano/pycardano/blob/main/integration-test/test/test_plutus.py#L239

**Comment by peterVG** [comment]
OMG. I tried everything but that :-)

Thanks very much @cffls I can confirm this works. Just one correction, the property name should be plural e.g. `builder.reference_inputs` not `builder.reference_input`

Will return favour with a documentation PR that you may or may not want to add.

**Comment by peterVG** [comment]
See PR https://github.com/Python-Cardano/pycardano/pull/119
