### ISSUE TITLE
Move to hashlib for hashing

### ISSUE THREAD

**Issue by nielstron** [Python-Cardano/pycardano#153]
**Is your feature request related to a problem? Please describe.** 
pycardano currently uses NaCL for its hashing primitives. This is usually a large library, that is also not pure python and often causes long builds during installation.

**Describe the solution you'd like**
The python standard library hashlib supports sha256 etc. It would be nice if they can be used by default.

**Describe alternatives you've considered**
None

**Additional context**
I want to make development on Cardano as accessible as possible and a short and easily installable toolchain is part of that.

**Comment by cffls** [comment]
We use NaCL also for signing&verification on curve ED25519, such as this example [here](https://github.com/Python-Cardano/pycardano/blob/main/pycardano/key.py#L154). Do you have some alternative libraries in mind that can do both signing and hashing? I can look into them.

**Comment by nielstron** [comment]
I realized that NaCl is used for signing too... Will check if there are lightweight alternatives :)
