### ISSUE TITLE
Allow str addresses as change address in txbuilder

### ISSUE THREAD

**Issue by nielstron** [Python-Cardano/pycardano#187]
**Is your feature request related to a problem? Please describe.**
A lot of users put a Bech32 encoded address as change address in the txbuilder, which seems natural as a user flow. The returned error message is usually quite obscure. 

**Describe the solution you'd like**
For this reason, the txbuilder should check and optimally directly transform a passed-in str object to a PyCardano address object to reduce friction.

**Describe alternatives you've considered**
The txbuilder could check that it is passed an address object and raise an error otherwise. The process to transform a string to address is very automatizable though, so it should directly apply this. 
 
**Additional context**
CC @while0x1

**Comment by cffls** [comment]
Looks like this issue will be resolved in the next release with this commit: https://github.com/Python-Cardano/pycardano/commit/4bf6a626f6f6093ae368b5bd980b1271d9cae4e4

Any string address passed to transaction output will be converted automatically.
