### ISSUE TITLE
Wrong variable used in the Plutus Smart Contract Tutorial

### ISSUE THREAD

**Issue by chrissiwaffler** [Python-Cardano/pycardano#197]
**Describe the bug**
in the last step of the [Smart Contract Tutorial](https://pycardano.readthedocs.io/en/latest/guides/plutus.html) when we want to submit the transaction for the “taker”, the variable `self.extended_payment_skey` is used but not defined.

**To Reproduce**
follow the steps by the tutorial

**Expected behavior**
The signing key of the second key pair should be used to sign and submit the transaction: `payment_skey_2`.
I don't know where the variable `self.extended_payment_skey` should come from.

**Environment and software version (please complete the following information):**
_shouldn't be relevant_
 - OS: MacOS 13.3.1
 - PyCardano Version 0.8.0

**Additional context**
Currently, learning opshin & pycardano, so I maybe I could have misunderstood something

**Comment by cffls** [comment]
Hi @chrissiwaffler , thanks for pointing out the problem in the tutorial. I've fixed it in this PR: https://github.com/Python-Cardano/pycardano/pull/200. Please let me know if you have any questions. Thanks!

**Comment by chrissiwaffler** [comment]
Nope, everything is clear!
PR looks good!
