### ISSUE TITLE
Improve Efficiency of Kupo UTxO Query by Directly Querying Unspent UTxOs

### ISSUE THREAD

**Issue by bhatt-deep** [Python-Cardano/pycardano#203]
**Is your feature request related to a problem? Please describe.**
Yes, the current implementation of the [_utxos_kupo](https://github.com/Python-Cardano/pycardano/blob/main/pycardano/backend/ogmios.py#L245-L274) method in the library is inefficient, as it retrieves all UTxOs and then filters for unspent ones. This can be slow and resource-intensive, especially when working with a large number of UTxOs.

**Describe the solution you'd like**
I propose updating the `_utxos_kupo` method to directly query unspent UTxOs using the `?unspent` flag in the endpoint. This would allow the library to retrieve only the unspent UTxOs, improving the efficiency and performance of the query.

**Describe alternatives you've considered**
NA

**Additional context**
NA

**Comment by henryyuanheng-wang** [comment]
Thanks for flagging this out! Looks like a flag introduced in the recent release. We'll incorporate it into the method.
