### ISSUE TITLE
RawPlutusData deepcopy error

### ISSUE THREAD

**Issue by juliusfrost** [Python-Cardano/pycardano#224]
**Describe the bug**
https://github.com/Python-Cardano/pycardano/blob/830090a1fca1276bca17c871ef0913112a1a4687/pycardano/txbuilder.py#L1212

During a `deepcopy` in the line above I get
`TypeError: cannot pickle '_cbor2.CBORTag' object`

This is because in my `tx_builder` one UTxO's datum is `'RawPlutusData(data=CBORTag(121, [1000]))'`

**To Reproduce**
```
git clone https://github.com/OpShin/opshin-pioneer-program.git
git checkout 81e0400 
poetry install
poetry run python src/week06/tests/test_negative_r_timed.py
```

**Logs**
https://github.com/OpShin/opshin-pioneer-program/actions/runs/4780231723/jobs/8497846594

**Expected behavior**
Shouldn't pickle should work on `CBORTag`? It doesn't look like a very complex data type.

**Environment and software version (please complete the following information):**
 - OS: Windows/Linux
 - PyCardano Version: latest

**Additional context**
Part of https://github.com/OpShin/opshin-pioneer-program/pull/43

**Comment by cffls** [comment]
CBORTag couldn't be pickled by default:

```
import cbor2
a = cbor2.CBORTag(121, [1000])
import copy
copy.deepcopy(a)
Traceback (most recent call last):
  File "/Applications/PyCharm.app/Contents/plugins/python/helpers/pydev/pydevconsole.py", line 364, in runcode
    coro = func()
  File "<input>", line 1, in <module>
  File "/opt/homebrew/Cellar/python@3.9/3.9.15/Frameworks/Python.framework/Versions/3.9/lib/python3.9/copy.py", line 161, in deepcopy
TypeError: cannot pickle '_cbor2.CBORTag' object
```

I will check if there is a quick fix to it.

**Comment by cffls** [comment]
This PR should be able to fix the problem: https://github.com/Python-Cardano/pycardano/pull/225

**Comment by juliusfrost** [comment]
> This PR should be able to fix the problem: https://github.com/Python-Cardano/pycardano/pull/225

Awesome, thanks!
