### ISSUE TITLE
Is it possible to implement conversions between different address types?

### ISSUE THREAD

**Issue by 99Kies** [Python-Cardano/pycardano#246]
how to get reward address with base address? and get base address with reward address.

<img width="1271" alt="image" src="https://github.com/Python-Cardano/pycardano/assets/45918704/3323d6e1-d6c9-42cf-aa37-1142d4799f2b">
<img width="1236" alt="image" src="https://github.com/Python-Cardano/pycardano/assets/45918704/47d89008-17a5-4393-a49a-d5f964a043bd">

**Comment by cffls** [comment]
An address is composed of two parts, payment and staking. Either part is optional. You can create both payment and staking address from an address that contains both parts. Example:

```python
>>> addr = Address.from_primitive("addr1q83ncas2uglxfkeawss86t5dhp8u32n6v90004wetfqn3lc78dd3kxwnk28zpwzyz6hkrflh9f7hqp79sf8lhvrsxlnqp06agx")
>>> Address(staking_part=addr.staking_part)
stake1uy0rkkcmr8fm9r3qhpzpdtmp5lmj5ltsqlzcynlmkpcr0essu3tsj
>>> Address(payment_part=addr.payment_part)
addr1v83ncas2uglxfkeawss86t5dhp8u32n6v90004wetfqn3lca9vcu3
```

**Comment by cffls** [comment]
[This page](https://pycardano.readthedocs.io/en/latest/guides/address.html) also provides some useful information about Cardano address.
