### ISSUE TITLE
cardano-cli ChainContext impl

### ISSUE THREAD

**Issue by thaddeusdiamond** [Python-Cardano/pycardano#250]
For those running a local cardano-node, using Python os.system() calls to shell out to cardano-cli and submit transactions/read from chain could be interesting.  Let me know if you would like a pull request for this, I can try to stub one out.  Just didn't want to proceed with coding if you had a good reason not to do this default impl in the library.

**Comment by nielstron** [comment]
I was thinking the same. Maybe check that all functions of the chaincontext can actually be implemented by the CLI, but I think it should work and would improve the library a lot :)

**Comment by cffls** [comment]
I think it is a good idea to expand the support of chain context in general. With that being said, I am not sure how stable the output of cardano-cli is. If it changes often, it means we will need to update pycardano accordingly as well.

**Comment by nielstron** [comment]
From my experience the output of cardano-cli has been pretty stable over the last 1.5 years. It should be fine to build on top of.

**Comment by KINGH242** [comment]
I added the cardano-cli chain context and submitted a pull request here #274.

The added code has tests as well, but I did not add any extra documentation yet.

**Comment by thaddeusdiamond** [comment]
Thanks! It looks really clean, well done.  Sorry I didn't get a chance to get to it in time.

**Comment by nielstron** [comment]
Closing, since #274 has been merged
