### ISSUE TITLE
genesisConfig request is made twice in OgmiosChainContext __init__

### ISSUE THREAD

**Issue by ross-spencer** [Python-Cardano/pycardano#283]
**Describe the bug**

The `genesisConfig` query is made twice in the OgmiosChainContext init:

https://github.com/Python-Cardano/pycardano/blob/9b5d367fddd6d370b508d2953dc67cf3deac4990/pycardano/backend/ogmios.py#L81-L82

Via: `self.genesis_param`.

This could be held within a variable in the `__init__` and then the attributes/dict values accessed independently. 

**To Reproduce**
Steps to reproduce the behavior. e.g. A python script.

Create an OgmiosChainContext and inspect the websocket requests made during initialization. 

**Logs**
If applicable, add logs to help explain your problem.

N/A. 

**Expected behavior**

The call should only be made once and the results accessed as many times as necessary for the genesisConfig. Alternatively, it should be made clearer in the docs/code if this is done for a specific reason.

**Environment and software version (please complete the following information):**
 - OS: [e.g. Ubuntu 20.04.3 LTS, Mac OS 12.1]
 - PyCardano Version [e.g. 0.1.1]

Python 3.10.12 + Pycardano 0.10.0.

**Additional context**

N/A.

**Comment by cffls** [comment]
`genesis_param` is a [cached property](https://github.com/Python-Cardano/pycardano/blob/9b5d367fddd6d370b508d2953dc67cf3deac4990/pycardano/backend/ogmios.py#L214-L221), so it won't be called twice in context initiation.

**Comment by ross-spencer** [comment]
> so it won't be called twice in context initiation.

I'm seeing two web-socket calls here, it's the only reason I traced it back to the init but I'll double check and send my logging next week.

**Comment by ross-spencer** [comment]
thanks for your patience @cffls, problem existed between user and keyboard. i was following some logic through incorrectly. Closing this.
