### ISSUE TITLE
tx sign fails without giving any explicit error. Error type: 500

### ISSUE THREAD

**Issue by reitcircles** [Python-Cardano/pycardano#298]
**Describe the bug**
Trying to sign this transaction. it fails silently without giving error
**To Reproduce**
Kindly check the txbuilder output. This tx fails to be signed.

**Logs**
`TransactionBuilder(context=<pycardano.backend.blockfrost.BlockFrostChainContext object at 0x7f5d5eba35b0>, utxo_selectors=[<pycardano.coinselection.RandomImproveMultiAsset object at 0x7f5d5e2b9b20>, <pycardano.coinselection.LargestFirstSelector object at 0x7f5d5e2b9400>], execution_memory_buffer=0.2, execution_step_buffer=0.2, ttl=None, validity_start=None, auxiliary_data=AuxiliaryData(data=AlonzoMetadata(metadata={721: {'f88faff05adf509c2ed47289f5b4bbb95796928bb8456b6330d7380a': {AssetName(b'(222)rcNFT'): {'description': 'Role NFT from reitcircles.com', 'name': '(222)rcNFT', 'image': 'QmRutrVt3hFTX56XBwet1uevc8gNGTYpChNpXxv9oyYCzi', 'tokenType': 'role'}}}}, native_scripts=None, plutus_scripts=None)), native_scripts=None, mint={ScriptHash(hex='f88faff05adf509c2ed47289f5b4bbb95796928bb8456b6330d7380a'): {AssetName(b'(100)rcNFT'): 1, AssetName(b'(222)rcNFT'): 1}}, required_signers=None, collaterals=[{'input': {
  'index': 1,
  'transaction_id': TransactionId(hex='c44e1113201927c3d079a98add29bb5a2f222e0889691291ed1433bc584d6d89'),
},
 'output': {
  'address': addr_test1qzh9j2qa7dny2rpjvgedvjmufaqndhgjejkmsmaatsdeufgd74hhzeetur4qr9v9e2mce0uxlzqelhuy9dq2027dh78ssquj4k,
  'amount': {'coin': 5000000, 'multi_asset': {}},
  'datum': None,
  'datum_hash': None,
  'post_alonzo': False,
  'script': None,
}}], certificates=None, withdrawals=None, reference_inputs=set(), _inputs=[{'input': {
  'index': 2,
  'transaction_id': TransactionId(hex='6fc171064584f0f1d95416f2031614d7de5c6da746e030cc19aad017b86a2bd7'),
},
 'output': {
  'address': addr_test1qzylgj0pzzm722x3vkp6nde7h5cuzt2m4g9c69n5dj0w5rqd74hhzeetur4qr9v9e2mce0uxlzqelhuy9dq2027dh78sgh34ld,
  'amount': {
    'coin': 874077053,
    'multi_asset': {ScriptHash(hex='fb23f71797eb9ed59172d89bba6a69ae97f9085d213033d9b9bb83c5'): {AssetName(b'sampleDao.001'): 8}},
  },
  'datum': None,
  'datum_hash': None,
  'post_alonzo': False,
  'script': None,
}}], _potential_inputs=[], _excluded_inputs=[], _input_addresses=[], _outputs=[{
  'address': addr_test1wz5wfllftz4sc5q5tedptegp0hs2kzvz9ddavfqp99gucnsvnwvkq,
  'amount': {
    'coin': 6000000,
    'multi_asset': {ScriptHash(hex='f88faff05adf509c2ed47289f5b4bbb95796928bb8456b6330d7380a'): {AssetName(b'(100)rcNFT'): 1}},
  },
  'datum': RoleDatum(roleName=b'General', subscriptionLevel=b'Tier1', expiryDate=1719595983, pubkeyhash=b'\x89\xf4I\xe1\x10\xb7\xe5(\xd1e\x83\xa9\xb7>\xbd1\xc1-[\xaa\x0b\x8d\x16tl\x9e\xea\x0c'),
  'datum_hash': None,
  'post_alonzo': False,
  'script': None,
}, {
  'address': addr_test1qrwcxmlx56njze57fjypt2f6q2ctpv2tvx2gf2mf866ajsasqj43gyduezd0crpju8l9ps4fuu94z0rp86t00c4m3nzs8yf0nd,
  'amount': {
    'coin': 6000000,
    'multi_asset': {ScriptHash(hex='f88faff05adf509c2ed47289f5b4bbb95796928bb8456b6330d7380a'): {AssetName(b'(222)rcNFT'): 1}},
  },
  'datum': None,
  'datum_hash': None,
  'post_alonzo': False,
  'script': None,
}], _fee=0, _datums={}, _collateral_return=None, _total_collateral=None, _inputs_to_redeemers={}, _minting_script_to_redeemers=[(b'Y\x04\xe3\x01\x00\x002"23t\xa9\x00\x01\xbb\x14\x98\xc8\xc8\xcc\xcc\x00@\x14\x92`\x03\x00%3\x00\x14\x89\x01\x08\x00\x13&3W8\x92\x01\x14NameError: validator\x00I\x8c\x8c\x8c\x88\x94\xcc\xd5\xcd\x19\xb8\xf0\x02H\x81\x01\x08\x00\x11\x0013\x00@\x02\x00\x12"#$\x98\xc8\xc9L\xcd\\\xd1\x91\x9b\x87225W:n\xa8\x00L\x94\xcc\x00R!\x01\x00\x00\x13&3W8\x92\x01\x0cNameError: p\x00I\x80\x04\x00L\x92\x00\x00\x01\x00\x1122S3W4dffJf\x00)\x11\x01\x03\x00\x13&3W8\x92\x01\x13NameError: has_utxo\x00I\x80\x04\xc8\xc8\xcc\xc8\xc0\x04\x00H\x89L\xcdU\xcf\x80\x08\x991\x9a\xb9\xc4\x91\nIndexError\x00I\x85L\xcd\\\xd1\x9b\x87\x00$\x80\x00M]\x08\x00\x89\x99\x80\x18\x01\x99\xb8\x10\x02H\x00\x8d]\x10\x00\xa4\x00\x06\xaa\xe7\x8d\xd5\x00\t\x92\x99\x80\nE\x01\x00\x00\x13&3W8\x92\x01\x0cNameError: p\x00I\x80\x04\x00L\x94\xcc\x00R!\x01\x07\x00\x13&3W8\x92\x01\x12NameError: context\x00I\x80\x04\x00@\x04@\x04L\x98\xcd\\\xe1\x92I\x11UTxO not consumed\x00\x00\x14\x98\x00@\x04L\x80\x04\x00L\x8c\x80\x08\xc8\xcc\xc9L\xc0\x05"\x01\x01\x02\x00\x13&3W8\x92\x01\x10NameError: print\x00I\x80\x04\xc9$\x01\x11ENTERED VALIDATOR\x00\x00\x10\x01\x00\x10\x0132""S3W4f\xe3\xc0\t"\x01\x01\x07\x00\x11\x001S3W4f\xe3\xc0\t"\x01\x01\t\x00\x11\x00AS3W4f\xe3\xc0\t"\x01\x01\x00\x00\x11\x00Q3\x00`\x02\x00\x10\x04\x000\x0222"S3W4f\xe3\xc0\t"\x01\x01\x03\x00\x11\x0013\x00@\x02\x00\x12"232S0\x01H\x81\x01\x01\x00\x13&3W8\x92\x01\x0eNameError: any\x00I\x80\x04\xc8\xcc\x8c\x8c\x00@\x04\x89L\xcdU\xcf\x80\x08\xa5\xeb@L\xd5\xd0\x18\x01\x9a\xba\x10\x013\x00 \x025t@\x02FFn\xbc\xc9L\xc0\x05"\x01\x01\x04\x00\x13&3W8\x92\x01\x0fNameError: oref\x00I\x80\x04\xc8\xc8\xcc\xc8\xc0\x04\x00H\x89L\xcdU\xcf\x80\x08\x991\x9a\xb9\xc4\x91\nIndexError\x00I\x85L\xcd\\\xd1\x9b\x87\x00$\x80\x00M]\x08\x00\x89\x99\x80\x18\x01\x99\xb8\x10\x02H\x00\x8d]\x10\x00\xa4\x00\x06\xaa\xe7\x8d\xd5\x00\t\x92\x99\x80\nE\x01\x06\x00\x13&3W8\x92\x01\x0cNameError: i\x00I\x80\x04\x00L\x88\x94\xcc\xd5\xcd\x19\xb8\xf0\x02H\x81\x01\x06\x00\x11\x0013\x00P\x02\x00\x10\x01223##\x00\x10\x01"S3Us\xe0\x02&\xecRa3W@`\x06j\xe8@\x04\xcc\x00\x80\x08\xd5\xd1\x00\t\x00\t\xba\xc33#\x00\x10\x01"%35W>\x00"d\xc6j\xe7\x12A\nIndexError\x00I\x85L\xcd\\\xd1\x9b\x87\x00$\x80\x00M]\x08\x00\x89\x99\x80\x18\x01\x99\xb8\x10\x02H\x00\x8d]\x10\x00\xa4\x00\x06\xaa\xe7\x8d\xd5\x00\t\x91\x91\x99\x91\x80\x08\x00\x91\x12\x99\x9a\xab\x9f\x00\x112c5s\x89!\nIndexError\x00I\x85L\xcd\\\xd1\x9b\x87\x00$\x80\x00M]\x08\x00\x89\x99\x80\x18\x01\x99\xb8\x10\x02H\x00\x8d]\x10\x00\xa4\x00\x06\xaa\xe7\x8d\xd5\x00\t\x92\x99\x80\nE\x01\x05\x00\x13&3W8\x92\x01\x12NameError: context\x00I\x80\x04\x00@\x04\x00@\x04\xc8\x00L\xc8\x88\x94\xcc\xd5\xcd\x19\xb8\xf0\x02H\x81\x01\x05\x00\x11\x001S3W4f\xe3\xc0\t"\x01\x01\x04\x00\x11\x00A3\x00P\x02\x00\x10\x03\x00##"%35sFn<\x00\x92!\x01\x02\x00\x11\x0013\x00@\x02\x00\x13"#5s\x80\x04f\xe9R\x00\x03v)0\x00\x99\x19\x11)\x99\xab\x9a3q\xe0\x04\x91\x01\x01\x01\x00\x11\x0013\x00@\x02\x00\x13"#3##\x00\x10\x01"%35W>\x00B\x00"f`\x06\x00f\xae\x88\x00\x8c\xc0\x10\x00M]\x08\x01\x11)\x99\xab\x9a\x00!J"\x00 \x04\x94\x00\x04\x00H\x80\x050\x01E\xd8y\x9f\xd8y\x9f\xd8y\x9fX o\xc1q\x06E\x84\xf0\xf1\xd9T\x16\xf2\x03\x16\x14\xd7\xde\\m\xa7F\xe00\xcc\x19\xaa\xd0\x17\xb8j+\xd7\xff\x02\xffJ(222)rcNFTJ(100)rcNFT\xff\x00\x01', {
  'data': {},
  'ex_units': {'mem': 0, 'steps': 0},
  'tag': {'__objclass__': <enum 'RedeemerTag'>, '_name_': 'MINT', '_value_': 1},
})], _inputs_to_scripts={}, _reference_scripts=[], _should_estimate_execution_units=True)

{'error': 'Internal Server Error', 'message': 'An unexpected response was received from the backend.', 'status_code': 500}
`

**Expected behavior**
Should have signed it successfully. 

**Environment and software version (please complete the following information):**
 - OS: 
 - Distributor ID:	Ubuntu
- Description:	Ubuntu 20.04.6 LTS
- Release:	20.04
- Codename:	focal
 - PyCardano Version [0.9.0]

**Additional context**

**Comment by cffls** [comment]
The error seems from blockfrost:

```
{'error': 'Internal Server Error', 'message': 'An unexpected response was received from the backend.', 'status_code': 500}
```

The tx was signed and submitted, but blockfrost ran into an internal server error. Blockfrost might be able to provide you with more information about why it failed internally.

**Comment by nielstron** [comment]
I think this is not an issue of pycardano, it is actually an issue of Blockfrost. We can not provide more details in case there is an internal server error at blockfrost.
