### ISSUE TITLE
Support for Ogmios 6.x in the ChainContext

### ISSUE THREAD

**Issue by nielstron** [Python-Cardano/pycardano#302]
**Is your feature request related to a problem? Please describe.**
Currently pycardano only supports Ogmios < 6.0.0 for the ChainContext but the API has changed since.

**Describe the solution you'd like**
There is an implementation of the OgmiosChainContext built by Viper Science [here](https://gitlab.com/viperscience/ogmios-python/-/blob/main/src/ogmios/chain_context.py) that could be used instead. I would suggest we inherit the code entirely and simply make ogmios package independent of pycardano and import it instead. We can then dynamically switch to their implementation if we find that the Ogmios client indicated is version >= 6.x

**Describe alternatives you've considered**
The user can be tasked directly to indicate the ogmios api version. Also, we could keep the ogmios and pycardano package seperate entirely.

**Additional context**
None

**Comment by ross-spencer** [comment]
hi @nielstron do you know when Ogmios 6 compatibility might be available at all?

**Comment by nielstron** [comment]
No this is currently not planned with high urgency because the [implementation by Viper-Science](https://gitlab.com/viperscience/ogmios-python/-/blob/main/src/ogmios/chain_context.py) is now pretty usable (after some fixes). I would recommend to use it.

**Comment by ross-spencer** [comment]
Great stuff, will take a look, thanks @nielstron
