### ISSUE TITLE
Mint tokens with plutus script

### ISSUE THREAD

**Issue by mateusap1** [Python-Cardano/pycardano#36]
I want to mint tokens with a plutus script I created, but I did not find any examples describing how to do so.

If it is already possible to mint tokens with plutus scripts I think the documentation is lacking references to that feature, I didn't find any examples on this repository or in the documentation.

As a work-around, I attempted to change the scripts from the transaction builder manually, but it returned me an exception saying I can't set attribute 'scripts'. Any plans on implementing that feature or is it there already, but I missed something? Also, any suggestions, however, for what to do meanwhile?

**Comment by 34r7h** [comment]
Agreed.. is there any way we can help? Atm, i'm dealing with a fragile and brittle key management solution to guarantee swaps of tokens for ada but I don't think it'll scale nearly as well as a script. Thanks for all the effort fellers!

**Comment by cffls** [comment]
Hi @mateusap1 , sorry about getting back to you late. Minting tokens with a script is a common use case. Ideally, we need txbuilder to provide a function that can take a minting script and a minting redeemer. I will add this function to txbuilder and create a minting example in the near future.

**Comment by cffls** [comment]
The example could be found in this integration test [here](https://github.com/cffls/pycardano/blob/55551580e0b8840617da8f2c8b32cc334020cc3d/integration-test/test/test_mint.py#L170). Closing this issue. Feel free to reopen if you have further questions.
