### ISSUE TITLE
Script Evaluation Error

### ISSUE THREAD

**Issue by theeldermillenial** [Python-Cardano/pycardano#360]
**Describe the bug**
In the last week or two, something has changed, potentially in BlockFrost. When evaluating a script for execution costs with a required signing key, pycardano puts in dummy values for both the key and the signature. However, now I am getting uninformative ScriptEvaluation errors when trying to evaluate. When I run it through Ogmios, I am told I am missing a required signing key.

**Environment and software version (please complete the following information):**
 - OS: Ubuntu 22.04
 - PyCardano Version = 0.10.0, but the error occurs on 0.11.1 as well

**Comment by nielstron** [comment]
Can you please share a minimal code snippet that reproduces the issue?
