### ISSUE TITLE
Multiple addresses from same keys

### ISSUE THREAD

**Issue by 34r7h** [Python-Cardano/pycardano#40]
Hey guys, not sure if this is the same question from those wanting wallets.

Is it possible to create multiple addresses from the same keys with this lib?

**Comment by cffls** [comment]
Hi @34r7h , if I understand correctly, you are asking for HD wallet? HD wallet is currently not available in this library. Although it is on our roadmap, there isn't a clear timeline when it will get implemented. If there are many requests for this feature, we might be able to prioritize it.

**Comment by 34r7h** [comment]
Thanks, Jerry. I understand building a wallet management feature is quite a workload and should be in high demand to warrant the effort. Perhaps a util function to derive new addresses from the key combo or existing addresses would be easier. As I understand, addresses are generated from the generated payment and staking keys, along with some meta data. 

Can you help me understand what the metadata is and if it impacts the uniqueness of a new address? Else, any direction on what crypto functions are used to derive new addresses from same keys would be awesome.

Cheers and force be with!

**Comment by cffls** [comment]
Hi @34r7h , you are right on the top level. In HD wallet, keys are derived deterministically from key paths. The "metadata" you mentioned is called "chain code" in the specification of HD wallet, [bip32](https://github.com/bitcoin/bips/blob/master/bip-0032.mediawiki). Cardano uses Ed25519 curve for its BIP32 implementation. The paper could be found [here](https://github.com/LedgerHQ/orakolo/blob/master/papers/Ed25519_BIP%20Final.pdf). I also found a python implementation of the paper [here](https://github.com/johnoliverdriscoll/py-edhd/blob/master/src/edhd/__init__.py). You will be able to use its code to derive new keys. In fact, the [signing implementation](https://github.com/cffls/pycardano/blob/main/pycardano/crypto/bip32.py) of extended key in pycardano uses a part of its code.

**Comment by 34r7h** [comment]
Thank you, Jerry.. you rock. I'll look into implementing that code and testing after my mvp testing is done. If it's straightforward, then I'll submit a pr for your consideration. Thanks agian!
