### ISSUE TITLE
Txs failing to build when there's minimal (but sufficient) coin.

### ISSUE THREAD

**Issue by 34r7h** [Python-Cardano/pycardano#52]
I have an address that contains 2.830539 ada. If i build a tx to send 1.6 ada, it fails with insufficient funds error. When I send 1.4 ada it works as expected. Seems the same with addresses holding more ada, as well. 

Since the tx fee should be ~0.16 ada and I'm sending more than the minimum 1 ada, I think this is a bug.

```
pycardano.exception.UTxOSelectionException: All UTxO selectors failed.
0|crypto |     Requested output:
0|crypto |      {'coin': 1795556, 'multi_asset': {}} 
0|crypto |     Pre-selected inputs:
0|crypto |      {'coin': 2830539, 'multi_asset': {}} 
0|crypto |     Additional UTxO pool:
0|crypto |      [] 
```

**Comment by 34r7h** [comment]
I thought this might have been because of ada locked in a token is showing as available, but I tried from an address with only lovelaces.

**Comment by cffls** [comment]
What version of pycardano are you using? It could be that the change (2.83-1.6-0.16=1.07) is not meeting the minimum utxo size requirement. It will be great if you can share the input address so I am able to reproduce the problem.

**Comment by 34r7h** [comment]
I'm using pycardano v0.5.0 sending from addr1qypm6f2z5g45duzj9v9lt7jz9ce2q5m59vw3reqm9e25uxpynes82004nuvufjx0zu8up9dlr574azfnnp2vj3dcwrsqfux5t0

**Comment by 34r7h** [comment]
I thought the min was 1 ADA + ~0.16 min tx fee. Does pycardano have a higher min to cover overhead without possible hiccups?

**Comment by cffls** [comment]
Could confirmed this is a bug. You are right, when there is only ADA in the output, 1 ADA is the minimum requirement. I fixed this in this commit: https://github.com/cffls/pycardano/commit/f8daca62f99325589aa190dea8803c7a8f8362c8

Test:

```python

from pycardano import *



network = Network.MAINNET
context = BlockFrostChainContext("mainnetqEZ4wDDoRdtWqh2SNVLNqfQbhlNmTbza", network)

address = Address.from_primitive('addr1qypm6f2z5g45duzj9v9lt7jz9ce2q5m59vw3reqm9e25uxpynes82004nuvufjx0zu8up9dlr574azfnnp2vj3dcwrsqfux5t0')

builder = TransactionBuilder(context)
builder.add_input_address(address)

builder.add_output(
    TransactionOutput(
        Address.from_primitive(
"addr1qyady0evsaxqsfmz0z8rvmq62fmuas5w8n4m8z6qcm4wrt3e8dlsen8n464ucw69acfgdxgguscgfl5we3rwts4s57ashysyee"
        ),
        Value.from_primitive(
            [
                1600000,
            ]
        ),
    )
)


tx_body = builder.build(change_address=address)
print(tx_body)
```

Output:

```
{'auxiliary_data_hash': None,
 'certificates': None,
 'collateral': None,
 'collateral_return': None,
 'fee': 167965,
 'inputs': [{'index': 0,
 'transaction_id': TransactionId(hex='1764ea2ce4653c1f03b78a5ac73cf4c40247a930f60d3467927f744e9c06fc6d')}],
 'mint': None,
 'network_id': None,
 'outputs': [{'address': addr1qyady0evsaxqsfmz0z8rvmq62fmuas5w8n4m8z6qcm4wrt3e8dlsen8n464ucw69acfgdxgguscgfl5we3rwts4s57ashysyee,
 'amount': {'coin': 1600000, 'multi_asset': {}},
 'datum_hash': None},
             {'address': addr1qypm6f2z5g45duzj9v9lt7jz9ce2q5m59vw3reqm9e25uxpynes82004nuvufjx0zu8up9dlr574azfnnp2vj3dcwrsqfux5t0,
 'amount': {'coin': 1062574, 'multi_asset': {}},
 'datum_hash': None}],
 'reference_inputs': None,
 'required_signers': None,
 'script_data_hash': None,
 'total_collateral': None,
 'ttl': None,
 'update': None,
 'validity_start': None,
 'withdraws': None}
```

**Comment by 34r7h** [comment]
Thanks Jer, I'll look for the update when you pull it into the master branch
