### ISSUE TITLE
How to calculate exact tx fee

### ISSUE THREAD

**Issue by 34r7h** [Python-Cardano/pycardano#53]
Forgive me if you already explained this in docs or examples.. how can I calculate the exact tx fee for given tx inputs, outputs, and metadata? 

It would be cool to have a method like ```Transaction.estimate_fee(builder)``` so I can inform users what they need to pay, especially considering their metadata inputs.

**Comment by cffls** [comment]
You can call `tx_body = txbuilder.build(change_address)`, and the fee in `tx_body.fee` will be the estimated fee. Remember that `txbuilder.build()` doesn't require signatures, and it is able to fake the witnesses based on the given transaction inputs and plutus scripts.

**Comment by 34r7h** [comment]
Thanks Jer!
