### ISSUE TITLE
How to consume UTxO from script address

### ISSUE THREAD

**Issue by grananqvist** [Python-Cardano/pycardano#8]
Hi, this looks like a great tool. But I don't see that it supports consuming UTxOs from script addresses?
To do that with the CLI, you need to set 
```
--tx-in-script-file FILE 
--tx-in-datum-file FILE 
--tx-in-redeemer-file FILE
 ```

but I don't see any corresponding arguments for that in this tool.
Is there any convenient way of doing this (possibly adding some source code) with the tool as it is now?
If this is not supported yet, what is the roadmap for adding this feature?
Thanks.

**Comment by grananqvist** [comment]
Update:
I found it in https://github.com/cffls/pycardano/blob/c87c689c99730934f057033c4654ef3a13af7873/pycardano/witness.py#L49

(it was not called datum). But `plutus_script`, `plutus_data` and `redeemer` don't seem to be used anywhere.

**Comment by astrojarred** [comment]
If I understood the roadmap/checklist in the readme correctly the software doesn't support interaction with Plutus Scripts yet, but it's planned.

**Comment by grananqvist** [comment]
Ah, I skipped that part 😅 . Looks like Plutus scripts are next on the roadmap.

**Comment by cffls** [comment]
Like Jarred (thanks for the quick answer!) mentioned, the library doesn't support creating transactions that involve Plutus scripts, but it is on the roadmap. The `plutus_data` field in `witness.py` is a placeholder, which makes sure the library is able to to decode CBOR of Plutus transactions.
