### ISSUE TITLE
minting, .cbor() error after update

### ISSUE THREAD

**Issue by 34r7h** [Python-Cardano/pycardano#86]
Hi Jer, I just upgraded to 0.6 and tested. I'm getting a new error around the minvalue function. Here's the traceback:
***
PythonShellError: AttributeError: 'BlockFrostChainContext' object has no attribute 'to_cbor'
0|crypto  |       at PythonShell.parseError (/Users/34r7h/a/cardano-python-js/node_modules/python-shell/index.js:295:21)
0|crypto  |       at terminateIfNeeded (/Users/34r7h/a/cardano-python-js/node_modules/python-shell/index.js:190:32)
0|crypto  |       at ChildProcess.<anonymous> (/Users/34r7h/a/cardano-python-js/node_modules/python-shell/index.js:182:13)
0|crypto  |       at ChildProcess.emit (events.js:314:20)
0|crypto  |       at Process.ChildProcess._handle.onexit (internal/child_process.js:276:12)
0|crypto  |       ----- Python Traceback -----
0|crypto  |       File "/Users/34r7h/a/cardano-python-js/python/mint.py", line 235, in <module>
0|crypto  |         min_val = min_lovelace(Value(0, my_nft), chain_context)
0|crypto  |       File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/pycardano/utils.py", line 119, in min_lovelace
0|crypto  |         return min_lovelace_post_alonzo(output, context)
0|crypto  |       File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/pycardano/utils.py", line 166, in min_lovelace_post_alonzo
0|crypto  |         constant_overhead + len(output.to_cbor("bytes")) {
0|crypto  |     traceback: 'Traceback (most recent call last):\n' +
0|crypto  |       '  File "/Users/34r7h/a/cardano-python-js/python/mint.py", line 235, in <module>\n' +
0|crypto  |       '    min_val = min_lovelace(Value(0, my_nft), chain_context)\n' +
0|crypto  |       '  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/pycardano/utils.py", line 119, in min_lovelace\n' +
0|crypto  |       '    return min_lovelace_post_alonzo(output, context)\n' +
0|crypto  |       '  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/pycardano/utils.py", line 166, in min_lovelace_post_alonzo\n' +
0|crypto  |       '    constant_overhead + len(output.to_cbor("bytes"))\n' +
0|crypto  |       "AttributeError: 'BlockFrostChainContext' object has no attribute 'to_cbor'\n",
***

**Comment by cffls** [comment]
Hi @34r7h , `min_lovelace` in 0.6 introduced a breaking change. The first parameter is now the chain context, so you will  need to modify your code in mint.py to:

```python
min_val = min_lovelace(chain_context, amount=Value(0, my_nft))
```

**Comment by 34r7h** [comment]
Thanks Jer, that resolves the .to_cbor error, however I'm seeing a different error now. Let's close this after updating the docs / examples. I'll make a new issue for the next error.

**Comment by cffls** [comment]
Close this issue as the proposed solution worked.
