### ISSUE TITLE
Tx submit errors with PlutusV2 script cbor derived from Helios

### ISSUE THREAD

**Issue by Et9797** [Python-Cardano/pycardano#88]
**Describe the bug**
Fails to claim UTxOs sitting at always succeed contract address. Blockfrost either returns malformed script errors or deserialize errors ("TooMuchSpace")

**To Reproduce**
See locking and claiming scripts:  https://github.com/Et9797/pycardano-issue
Cbor hex obtained from Helios: 54530100003222233335734600893124c4c9312511
The Helios contract:
`spending always_true

func main() -> Bool {
    true
}
`
**Environment and software version (please complete the following information):**
Pycardano 0.6.2.
Preview testnet

**Comment by Et9797** [comment]
Solved the problem with generous help of the Helios dev. Pycardano was deriving the wrong script address. Removing the first 2 cbor digits solves the problem and generates the correct script address in Pycardano.

**Comment by Et9797** [comment]
Error still persists if using longer contracts. Cardano-cli and Helios return the same address

**Comment by cffls** [comment]
Thanks @Et9797 ! Took at quick look at [the code](https://github.com/Et9797/pycardano-issue/blob/main/claim.py#L24), it seems like you load the cbor script with `bytes.fromhex()`, but the right way is to use `cbor2.loads` on top of it, which looks like this:

```
script = PlutusV2Script(cbor2.loads(bytes.fromhex(cbor_hex)))
``` 

The rule of thumb is to load the script with `cbor2.loads` whenever it is a cbor :D
