### ISSUE TITLE
Error sending simple Tx of tADA

### ISSUE THREAD

**Issue by QuixoteSystems** [Python-Cardano/pycardano#90]
**Describe the bug**
I'm trying to send some tADA on PreProd context but I got this error. If I try to send the same CBOR signed Tx using curl and Blockfrost API I get the same error.

**To Reproduce**
My code (it is a simple example test):

~~~

NETWORK = Network.TESTNET

context = BlockFrostChainContext(
    project_id="preproXXXXXXXXXXXXXXXXXXXXXX",
    network=NETWORK,
    base_url="https://cardano-preprod.blockfrost.io/api",
)

# Read keys to memory
# Assume there is a payment.skey file sitting in current directory
psk = PaymentSigningKey.load("payment.skey")
pvk = PaymentVerificationKey.from_signing_key(psk)

# Wallet in the node (sender)
wallet = "addr_test1vrppcwynx539fvwpppXXXXXXXXXXXXXXXXX"

# Create a transaction builder
builder = TransactionBuilder(context)

# Tell the builder that transaction input will come from a specific address, assuming that there are some ADA and native
builder.add_input_address(wallet)

# Get all UTxOs currently sitting at this address
utxos = context.utxos(wallet)

builder.add_input(utxos[0])

# Nami Wallet
nami ="addr_test1qr6uhu9ru5v0XXXXXXXXXXXXXXXX"

# Send 1.5 ADA to a Nami address.
builder.add_output( TransactionOutput.from_primitive([nami, 1500000]))

# Create final signed transaction
signed_tx = builder.build_and_sign([psk], change_address=billetera)

print("############### Transaction created ###############")
print(f"Tx: {signed_tx}")
print(f"Signed Tx: {signed_tx.to_cbor()}")

# Submit signed transaction to the network
print("############### Submitting transaction ###############")
context.submit_tx(signed_tx.to_cbor())
~~~

**Error**
~~~

blockfrost.utils.ApiError: {'error': 'Bad Request', 'message': '"transaction read error RawCborDecodeError [DecoderErrorDeserialiseFailure \\"Byron Tx\\" (DeserialiseFailure 1 \\"Size mismatch when decoding TxAux.\\\\nExpected 2, but found 4.\\"),DecoderErrorDeserialiseFailure \\"Shelley Tx\\" (DeserialiseFailure 1 \\"Size mismatch when decoding \\\\nRecord RecD.\\\\nExpected 4, but found 3.\\"),DecoderErrorDeserialiseFailure \\"Shelley Tx\\" (DeserialiseFailure 1 \\"Size mismatch when decoding \\\\nRecord RecD.\\\\nExpected 4, but found 3.\\"),DecoderErrorDeserialiseFailure \\"Shelley Tx\\" (DeserialiseFailure 1 \\"Size mismatch when decoding \\\\nRecord RecD.\\\\nExpected 4, but found 3.\\"),DecoderErrorDeserialiseFailure \\"Shelley Tx\\" (DeserialiseFailure 108 \\"expected string\\"),DecoderErrorDeserialiseFailure \\"Shelley Tx\\" (DeserialiseFailure 108 \\"expected string\\")]"', 'status_code': 400}
~~~

**Environment and software version (please complete the following information):**
 - OS: [Ubuntu 20.04.3 LTS]
 - PyCardano Version [0.6.2]

**Comment by cffls** [comment]
Hi @QuixoteSystems , the code above looks okay to me. Could you provide the cbor hex so I can help debug further? Thanks!

**Comment by QuixoteSystems** [comment]
Yes, you have here. Thanks a lot for your help!

This is the Signed Tx CBOR: 84a300818258207a0ff650a98509f50c668e8d695ee0c295e23f9fe425c92aa4a1ad483c5d604b00018282583900f5cbf0a3e518fc57aec9d6ff992e084610aedbbc53695c4d200c0c3ef82279ce53de2055ab74a4597fe1f4f5f03b54062bfe81b6ad64c5a21a0016e36082783f616464725f7465737431767270706377796e78353339667677707070736c657935736e74736171767a6a7732326133307638356730757a73637739356c37761b0000000253f26f23021a0002917da100818258206cacfb386c50ffda303151d0c20efa30e95a903483e6219072a3ce536fd2972058401b024eb623f028f4733a3cb416ed55f105a89748354e91fbdf74ffa4e8f1697b4a12edbd076da3b510822c47234616142bde5729bedfbf3f366d7f0f5be8b005f5f6

**Comment by cffls** [comment]
Thanks @QuixoteSystems , I decoded the CBOR you provided, and it looks like the problem is that the change address is incorrectly formatted:

```
[
  {
    "0": [
      [
        "z\u000f\\xf6P\\xa9\\x85\t\\xf5\ff\\x8e\\x8di^\\xe0\\xe2?\\x9f\\xe4%\\xc9*\\xa4\\xa1\\xadH<]`K",
        0
      ]
    ],
    "1": [
      [
        "\u0000\\xf5\\xcb\\xf0\\xa3\\xe5\u0018\\xfcW\\xae\\xc9\\xd6\\xff\\x99.\bF\u0010\\xaeۼSi\\M \f\f>\\xf8\"y\\xceS\\xde U\\xabt\\xa4Y\u007f\\xe1\\xf4\\xf5\\xf0;T\u0006+\\xfe\\x81\\xb6\\xaddŢ",
        1500000
      ],
      [
        "addr_test1vrppcwynx539fvwpppsley5sntsaqvzjw22a30v85g0uzscw95l7v", <-------- This is incorrect
        9998331683
      ]
    ],
    "2": 168317
  },
  {
    "0": [
      [
        "l\\xac\\xfb8lP\\xff\\xda01Q\\xd0\\xc2\u000e\\xfa0\\xe9Z\\x904\\x83\\xe6!\\x90r\\xa3\\xceSoҗ ",
        "\u001b\u0002N\\xb6#\\xf0(\\xf4s:<\\xb4\u0016\\xedU\\xf1\u0005\\xa8\\x97H5N\\x91\\xfb\\xdft\\xff\\xa4\\xe8\\xf1i{J\u0012\\xed\\xbd\u0007m\\xa3\\xb5\u0010\\x82,G#F\u0016\u0014+\\xdeW)\\xbe߿?6m\u007f\u000f[\\xe8\\xb0\u0005"
      ]
    ]
  },
  true,
  null
]
``` 

I am not sure how `billetera` was created, but I guess its value is `addr_test1vrppcwynx539fvwpppsley5sntsaqvzjw22a30v85g0uzscw95l7v` and its type is string. You want to make sure its type is `Address` by something like this: 

```python
billetera=Address.from_primitive("addr_test1vrppcwynx539fvwpppsley5sntsaqvzjw22a30v85g0uzscw95l7v")
```

**Comment by QuixoteSystems** [comment]
You are completely right! 😄  I was wrong. I thought that you can manage an address like a string because and saw this:

~~~~
utxos = context.utxos(str(address))
~~~~

Then I thought: well just I can have wallet address variable like an string... Now I see, we need an address object and then cast to string when we need.

Perfect, thanks a lot for your help. This project is useful and really necessary to develop Cardano. I will try to help to you in this project. If you have suggestions or some list TODO, I can try.

**Comment by cffls** [comment]
Thanks for your kind words! I have some TODOs in mind, but would like to formalize them into Github projects. If you want to work on something now, this Github issue is actually a good starting point. This error occurred when a string is passed to the Address argument of `TransactionOutput`. It could've been avoided if a check/conversion is added to its [post init](https://github.com/cffls/pycardano/blob/main/pycardano/transaction.py#L376), where it checks and converts the string to an address type.

**Comment by QuixoteSystems** [comment]
Ok, perfect! then I will work on it and I will send a PR when is done.

**Comment by cffls** [comment]
Thank you! Closing this issue as the root cause of the problem is not in the library itself.
