### ISSUE TITLE
Size mismatch when decoding errors on fairly simple multi_asset transaction with builder

### ISSUE THREAD

**Issue by CardanoDur** [Python-Cardano/pycardano#97]
**Describe the bug**
I'm essentially following the example for tx_builder in github.  I'm not seeing anything that jumps out in the signedTX that looks wrong, the builder is identifying the correct UTXOs and formating the proper outputs.  Put I'm getting a 400 error from Blockfrost:

`blockfrost.utils.ApiError: {'error': 'Bad Request', 'message': '"transaction read error RawCborDecodeError [DecoderErrorDeserialiseFailure \\"Byron Tx\\" (DeserialiseFailure 1 \\"Size mismatch when decoding TxAux.\\\\nExpected 2, but found 4.\\"),DecoderErrorDeserialiseFailure \\"Shelley Tx\\" (DeserialiseFailure 1 \\"Size mismatch when decoding \\\\nRecord RecD.\\\\nExpected 4, but found 3.\\"),DecoderErrorDeserialiseFailure \\"Shelley Tx\\" (DeserialiseFailure 1 \\"Size mismatch when decoding \\\\nRecord RecD.\\\\nExpected 4, but found 3.\\"),DecoderErrorDeserialiseFailure \\"Shelley Tx\\" (DeserialiseFailure 1 \\"Size mismatch when decoding \\\\nRecord RecD.\\\\nExpected 4, but found 3.\\"),DecoderErrorDeserialiseFailure \\"Shelley Tx\\" (DeserialiseFailure 155 \\"expected string\\"),DecoderErrorDeserialiseFailure \\"Shelley Tx\\" (DeserialiseFailure 155 \\"expected string\\")]"', 'status_code': 400}`

**To Reproduce**
```
import util
from pycardano import (
    Address,
    PaymentSigningKey,
    PaymentVerificationKey,
    Transaction,
    TransactionBody,
    TransactionBuilder,
    TransactionInput,
    TransactionOutput,
    TransactionWitnessSet,
    Value,
    VerificationKeyWitness,
    BlockFrostChainContext,
    Network
)
network = Network.MAINNET
context = BlockFrostChainContext(util.blockfrostHeader['project_id'], network)
address = 'addr1v9f3a4hf85s2xdy355n7sv0qjkp6mj785zca2m03cqvt4kqqthpgu'
toAddress = 'addr1vy65aqt766xp9u38hy2l7t2ejqtep8g799efh9uwu78askgpfzqtr'

sk = PaymentSigningKey.load("payment.skey")

builder = TransactionBuilder(context)
builder.add_input_address(Address.from_primitive(address))
# utxos = context.utxos(str(address))
# builder.add_input(utxos[0])
# builder.add_input(utxos[1])
builder.add_output(
    TransactionOutput(
        Address.from_primitive(
            toAddress
        ),
        Value.from_primitive(
            [
                1500000,
                {
                    bytes.fromhex(
                        "c9281d64953f9531304e57e4ff15111f0c5445167c0b413f70fcd50c"  # Policy ID
                    ): {
                        b"RUNE": 20  # Asset name and amount
                    }
                },
            ]
        ),
    )
)

signedTX = builder.build_and_sign([sk], change_address=address)
context.submit_tx(signedTX.to_cbor())
```

**Logs**
signed_tx (not cbor-ed):
```
{
  'auxiliary_data': None,
  'transaction_body': {
    'auxiliary_data_hash': None,
    'certificates': None,
    'collateral': None,
    'collateral_return': None,
    'fee': 171793,
    'inputs': [
      {
        'index': 1,
        'transaction_id': TransactionId(hex='8f0443226a68631d2919ec32378d4f7aa231a054d027260c9bebdc90b513a550'),
      },
      {
        'index': 0,
        'transaction_id': TransactionId(hex='a1887376d765595098fb049ddff4c950dabb5184989836c1599d64bbf0d67759'),
      },
    ],
    'mint': None,
    'network_id': None,
    'outputs': [
      {
        'address': addr1vy65aqt766xp9u38hy2l7t2ejqtep8g799efh9uwu78askgpfzqtr,
        'amount': {
          'coin': 1500000,
          'multi_asset': {ScriptHash(hex='c9281d64953f9531304e57e4ff15111f0c5445167c0b413f70fcd50c'): {AssetName(b'RUNE'): 20}},
        },
        'datum': None,
        'datum_hash': None,
        'post_alonzo': False,
        'script': None,
      },
      {
        'address': 'addr1v9f3a4hf85s2xdy355n7sv0qjkp6mj785zca2m03cqvt4kqqthpgu',
        'amount': {
          'coin': 10382691,
          'multi_asset': {ScriptHash(hex='c9281d64953f9531304e57e4ff15111f0c5445167c0b413f70fcd50c'): {AssetName(b'RUNE'): 980}},
        },
        'datum': None,
        'datum_hash': None,
        'post_alonzo': False,
        'script': None,
      },
    ],
    'reference_inputs': None,
    'required_signers': None,
    'script_data_hash': None,
    'total_collateral': None,
    'ttl': None,
    'update': None,
    'validity_start': None,
    'withdraws': None,
  },
  'transaction_witness_set': {
    'bootstrap_witness': None,
    'native_scripts': None,
    'plutus_data': None,
    'plutus_v1_script': None,
    'plutus_v2_script': None,
    'redeemer': None,
    'vkey_witnesses': [
      {
        ************REDACTED*************************
      },
    ],
  },
  'valid': True,
}
```

**Expected behavior**
Expect the transaction to go through

**Environment and software version (please complete the following information):**
 - OS:  Win 11 for dev, Ubuntu 20.4.5 prod
 - PyCardano 0.6.3

**Additional context**

**Comment by CardanoDur** [comment]
Nevermind, I saw my error immediately after putting it in here.  They should really have way in Github to have you type out your issue, but do a pseudo submission b/c invariably you'll see what you did wrong the second you submit.

**Comment by cffls** [comment]
This is the same issue as https://github.com/cffls/pycardano/issues/90, where address passed to change should be `Address` type instead of `str`.

**Comment by CardanoDur** [comment]
yeah, I had gone over #90 as well.  I changed the code to use from_primative but missed one.  If only you could delete issues
